language: haxe
sudo: false
dist: trusty
haxe:
 - development

install:
 - haxelib git vshaxe-build https://github.com/vshaxe/vshaxe-build

script:
 - haxelib run vshaxe-build -t hxparser -v -m both
 - git clone https://github.com/HaxeFoundation/haxe haxe-git --depth 1
 - node bin/test.js haxe-git